<?php
  $pagename = 'Temiar (SIL) Keyboard Help';
  $pagetitle = $pagename;
  require_once('header.php');
?>
<p>Temiar keyboard layout generated by template.</p>

<h2>Desktop Keyboard Layout</h2>
<div id='osk' data-states='default shift'>
</div>
