<?php 
  $pagename = 'Wakhi Standard Keyboard Help';
  $pagetitle = $pagename;
  // Header we will tidy up later  
  require_once('header.php');
?>
<p>
Wakhi Standard scientific keyboard provides an easy approach to write Wakhi With latin greeco assisted letter to specifically nominated each sound.
This script was generated by stabline kamensky and gruun berg and has been extensively in use by following scholars and native writer in Pakistan 
and Tajikistan. Most of the written Wakhi content is in this script.</p>

<p>We provide easy way to write the specific Wakhi letters by double pressing the related key and in some cases ;+t and ;+d. </p>

<p>We have also replace gamma greek with gamma latin to avoid confusion with y.
</p>
<h1>Keyboard Layout</h1>

<h2>Desktop Keyboard Layout</h2>
<p>This keyboard makes use of a deadkey (;). You can type the deadkey plus a letter to output another letter. For example, typing ";g" will produce "ɣ". The deadkey can be used with c, d, g, j, s, t, x, z to produce čδɣǰšθx̌ž respectively. These are also available for capital letters. Additionally, typing ";/" will produce ы́.</p>
<p>The keyboard also makes use of typing double letters to produce a different output. For example, typing "uu" will output "ʉ". The double letters that are available are c, d, e, g, j, s, t, u, x, z to produce č̣ḍəɣ̌ǰ̣ṣ̌ʉx̌ẓ̌ respectively. These are also available for capital letters.</p>
<p>Typing "dz" or "DZ" will produce ʒƷ respectively.</p>
<p>Lastly, an acute accent is available by typing a "`" after the vowel. For example typing "a`" will produce á. This is available with a, e, i, o, and u. Additionally, typing "u/" and "e/" will produce "ʉ́ə́" respectively.</p>

<div id='osk' data-states='default shift'>
</div>


<h2>Mobile/Phone Keyboard Layout</h2>
<p>Due to the size and number of keys, some characters are hidden in the long press. 
	Press and hold on the key with a little dot on the top right to reveal and use them.</p>

<div id='osk-phone' data-states='default shift numeric'>
</div>

<p>© Masood Karim</p>

</body>
</html>